-- Database initialization for orange_db
CREATE DATABASE IF NOT EXISTS orange_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE orange_db;

-- Department table
CREATE TABLE IF NOT EXISTS department (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  dept_code VARCHAR(32) NOT NULL UNIQUE,
  dept_name VARCHAR(64) NOT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Location space table
CREATE TABLE IF NOT EXISTS location_space (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  dept_id BIGINT NOT NULL,
  room_no VARCHAR(32) NOT NULL,
  area DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_location_dept_id (dept_id),
  UNIQUE KEY uk_dept_room (dept_id, room_no),
  CONSTRAINT fk_location_dept
    FOREIGN KEY (dept_id) REFERENCES department(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Assignee table
CREATE TABLE IF NOT EXISTS assignee (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  emp_no VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  phone VARCHAR(32) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Asset table
CREATE TABLE IF NOT EXISTS asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  asset_no VARCHAR(32) NOT NULL UNIQUE,
  asset_name VARCHAR(64) NOT NULL,
  value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  location_id BIGINT NOT NULL,
  assignee_id BIGINT DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0=idle,1=assigned',
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_asset_location (location_id),
  INDEX idx_asset_assignee (assignee_id),
  INDEX idx_asset_status (status),
  CONSTRAINT fk_asset_location
    FOREIGN KEY (location_id) REFERENCES location_space(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_asset_assignee
    FOREIGN KEY (assignee_id) REFERENCES assignee(id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
